- hosts: web
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Create index.html
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Hello from {{ env }} Environment - Powered by Terraform & Ansible & NGINX</h1>"

    - name: Ensure NGINX is running and enabled
      service:
        name: nginx
        state: started
        enabled: yes